In [1]:
import os

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

import tensorflow as tf

In [2]:
# export CUDA_VISIBLE_DEVICES=1
# os.environ["CUDA_VISIBLE_DEVICES"]="1"
gpus = tf.config.list_physical_devices("GPU")
print(gpus)
tf.config.experimental.set_virtual_device_configuration(gpus[0], 
[tf.config.experimental.VirtualDeviceConfiguration(memory_limit=3300)])

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [6]:
# Initialization
x = tf.constant(4, shape=(1, 1), dtype=tf.float32)
print(x)

x = tf.constant([[1, 2, 3], [4, 5, 6]], shape=(2, 3))
print(x)

x = tf.eye(3)
print(x)

x = tf.ones((4, 3))
print(x)

x = tf.zeros((3, 2, 5))
print(x)

x = tf.random.uniform((2, 2), minval=0, maxval=1)
print(x)

x = tf.random.normal((3, 3), mean=0, stddev=1)
print(tf.cast(x, dtype=tf.float64))
# tf.float (16,32,64), tf.int (8, 16, 32, 64), tf.bool

x = tf.range(9)
x = tf.range(start=0, limit=10, delta=2)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(4, 3), dtype=float32)
tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 2, 5), dtype=float32)
tf.Tensor(
[[0.7361008  0.8921968 ]
 [0.6271645  0.14847612]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 0.47951019 -0.06018141  0.81822765]
 [ 0.6314612   0.22162588  1.1098088 ]
 [-0.85259312  0.36404818  0.50418895]], shape=(3, 3), dtype=float64)
tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)


In [8]:
# Math
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])

print(f"x = {x}")
print(f"y = {y}")

z = tf.add(x, y)
z = x + y
print(f"x+y = {z}")

z = tf.subtract(x, y)
z = x - y
print(f"x-y = {z}")

z = tf.divide(x, y)
z = x / y
print(f"x/y = {z}")

z = tf.multiply(x, y)
z = x * y
print(f"x*y = {z}")

z = tf.tensordot(x, y, axes=1)
print(f"x dot y  = {z}")

z = x ** 5
print(f"x^5  = {z}")

x = tf.random.normal((2, 3))
y = tf.random.normal((3, 2))
z = tf.matmul(x, y)
z = x @ y
print(f"x @ y  = {z}")

x = tf.random.normal((2, 2))
print(f"rand normal 2x2 tensor  = {z}")

x = [1 2 3]
y = [9 8 7]
x+y = [10 10 10]
x-y = [-8 -6 -4]
x/y = [0.11111111 0.25       0.42857143]
x*y = [ 9 16 21]
x dot y  = 46
x^5  = [  1  32 243]
x @ y  = [[ 1.1985385   2.5683093 ]
 [ 0.10066936 -0.14050534]]
rand normal 2x2 tensor  = [[ 1.1985385   2.5683093 ]
 [ 0.10066936 -0.14050534]]


In [5]:
# Indexing
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
print(x[:])
print(x[1:])
print(x[1:3])
print(x[::2])
print(x[::-1])

indices = tf.constant([0, 3])
x_indices = tf.gather(x, indices)

x = tf.constant([[1, 2], [3, 4], [5, 6]])

print(x[0, :])
print(x[0:2, :])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [10]:
# Reshaping
x = tf.range(9)
print(f"x={x}")

x = tf.reshape(x, (3, 3))
print(f"x reshaped to 3x3 tensor = \n{x}")

x = tf.transpose(x, perm=[1, 0])
print(f"x transposed = \n{x}")

x=[0 1 2 3 4 5 6 7 8]
x reshaped to 3x3 tensor = 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
x transposed = 
[[0 3 6]
 [1 4 7]
 [2 5 8]]
